apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alpine
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: git@github.com:neocycf/test.git
      revision: HEAD
      files:
      - path: "dir1/prod/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-alpine'
    spec:
      project: default
      source:
        repoURL: git@github.com:neocycf/test.git
        targetRevision: HEAD
        path: "dir1/apps/guestbook"
      destination:
        #server: https://kubernetes.default.svc
        #: '{{cluster.address}}'
        name: '{{cluster.name}}'
        namespace: default
