apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alpine
spec:
  generators:
    - git:
        repoURL: https://github.com/neocycf/test.git
        revision: HEAD
        files:
        - path: "test/dir1/prod/config.json"
        - path: "test/dir1/prod-2/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-alpine'
    spec:
      project: default
      source:
        repoURL: https://github.com/neocycf/test.git
        targetRevision: HEAD
        path: "test/dir1/app"
      destination:
        server: https://kubernetes.default.svc
        #server: '{{cluster.address}}'
        namespace: default
