apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - git:
        repoURL: https://github.com/neocycf/test.git
        revision: HEAD
        files:
        - path: "example/cluster-config/engineering/prod/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/neocycf/test.git
        targetRevision: HEAD
        path: "example/apps/guestbook"
      destination:
        server: https://kubernetes.default.svc
        #server: '{{url}}'
        #server: '{{cluster.address}}'
        namespace: default
